### ISSUE TITLE
Chunk did not load when there is a blocks from electricity

### ISSUE THREAD

**Issue by DejFidOFF** [anluin/Electricity#10]
Chunk did not load when there is a blocks from electricity

VS 1.19.7 electricity 0.11

Server returns error

17.4.2024 13:26:49 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.RebuildNetwork(MechanicalNetwork network, IMechanicalPowerDevice nowRemovedNode) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 233
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.Event_ChunkDirty(Vec3i chunkCoord, IWorldChunk chunk, EnumChunkDirtyReason reason) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 289
   at Vintagestory.Server.ServerSystemSupplyChunks.mainThreadLoadChunkColumn(ChunkColumnLoadRequest chunkRequest) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 894
   at Vintagestory.Server.ServerSystemSupplyChunks.<>c__DisplayClass15_0.<loadOrGenerateChunkColumn_OnChunkThread>b__0() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 696
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2782
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 893
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

![image_electr](https://github.com/anluin/Electricity/assets/98642082/39cbec86-51a1-47c7-9fed-1750046fba53)

**Comment by DejFidOFF** [comment]
Again and again and again. Eating chunks at the server...

15.5.2024 21:39:57 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.RebuildNetwork(MechanicalNetwork network, IMechanicalPowerDevice nowRemovedNode) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 204
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.Event_ChunkDirty(Vec3i chunkCoord, IWorldChunk chunk, EnumChunkDirtyReason reason) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 289
   at Vintagestory.Server.ServerSystemSupplyChunks.mainThreadLoadChunkColumn(ChunkColumnLoadRequest chunkRequest) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 894
   at Vintagestory.Server.ServerSystemSupplyChunks.<>c__DisplayClass15_0.<loadOrGenerateChunkColumn_OnChunkThread>b__0() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 696
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2782
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 893
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

15.5.2024 20:11:00 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.RebuildNetwork(MechanicalNetwork network, IMechanicalPowerDevice nowRemovedNode) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 204
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.Event_ChunkDirty(Vec3i chunkCoord, IWorldChunk chunk, EnumChunkDirtyReason reason) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 289
   at Vintagestory.Server.ServerSystemSupplyChunks.mainThreadLoadChunkColumn(ChunkColumnLoadRequest chunkRequest) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 894
   at Vintagestory.Server.ServerSystemSupplyChunks.<>c__DisplayClass15_0.<loadOrGenerateChunkColumn_OnChunkThread>b__0() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 696
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2782
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 893
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

15.5.2024 09:54:14 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.RebuildNetwork(MechanicalNetwork network, IMechanicalPowerDevice nowRemovedNode) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 233
   at Vintagestory.GameContent.Mechanics.MechanicalPowerMod.Event_ChunkDirty(Vec3i chunkCoord, IWorldChunk chunk, EnumChunkDirtyReason reason) in VSSurvivalMod\Systems\MechanicalPower\MechanicalPowerMod.cs:line 289
   at Vintagestory.Server.ServerSystemSupplyChunks.mainThreadLoadChunkColumn(ChunkColumnLoadRequest chunkRequest) in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 894
   at Vintagestory.Server.ServerSystemSupplyChunks.<>c__DisplayClass15_0.<loadOrGenerateChunkColumn_OnChunkThread>b__0() in VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 696
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks() in VintagestoryLib\Server\ServerMain.cs:line 2782
   at Vintagestory.Server.ServerMain.ProcessMain() in VintagestoryLib\Server\ServerMain.cs:line 893
   at Vintagestory.Server.ServerMain.Process() in VintagestoryLib\Server\ServerMain.cs:line 886

**Comment by DejFidOFF** [comment]
Any solution?
